tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      # Execute your AWS environment setup script
      /workspace/aws-bootcamp-cruddur-2023/aws_env_setup.sh

vscode:
  extensions:
    - 42Crunch.vscode-openapi
